config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'エイム' },
    { id: 3, name: '立ち回り' },
    { id: 4, name: 'スキル、アルティメット' },
    { id: 5, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :questions

end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  
  validates :title,   presence: true
  validates :content, presence: true
  validates :genre_id, numericality: { other_than:1 , message: "can't be blank" }

  def self.search(search)
    if search != ""
      Question.where('title LIKE(?)', "%#{search}%").or(Question.where('content LIKE(?)', "%#{search}%"))
    else
      Question.all
    end
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :questions
  has_many :comments

  validates :nickname, presence: true
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password, confirmation: true, length: { minimum: 6, allow_blank: true }, format: { with: VALID_PASSWORD_REGEX, allow_blank: true}
  VALID_NAME_REGEX = /\A[ぁ-んァ-ヶ一-龥々ー]+\z/.freeze
  validates :birthday, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile, :birthday])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    redirect_to "/questions/#{params[:question_id]}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, question_id: params[:question_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :move_to_index, except: [:index, :new, :create, :show, :search]
  def index
    @questions = Question.all.order(id: "DESC")
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @comment = Comment.new
    @comments = @question.comments.includes(:user)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    question = Question.find(params[:id])
    if question.update(question_params)
      redirect_to root_path
    end
  end

  def destroy
    question = Question.find(params[:id])
    if question.destroy
      redirect_to root_path
    end
  end

  def search
    @questions = Question.search(params[:keyword])
  end

  private
  def question_params
    params.require(:question).permit(:title, :content, :genre_id).merge(user_id: current_user.id)
  end

  def move_to_index
    @question = Question.find(params[:id])
    if current_user.id != @question.user.id
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @questions = Question.where(user_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameQuestion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<%= link_to 'Game Question', root_path, class: "logo" %>
<div class="question-form-main">
  <h1 class="question-form-headline">質問編集フォーム</h1>
  <div class="question-form">
    <%= form_with model: @question, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <%= f.text_area :title, placeholder:"質問を入力してください(60字まで)", class:"title-form", maxlength:"60" %>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
      <%= f.text_area :content, placeholder:"質問の具体的な内容を入力してください", rows: "8", class:"content-form" %>
      <%= f.submit "投稿する", class:"submit-btn" %>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<%= render "shared/header" %>
<div class="upper-contents">
  <div class="search-form">
    <%= form_with(url: search_questions_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <div class="question-btn">
    <%= link_to '質問を投稿する', new_question_path, class:"question-form-btn" %>
  </div>
</div>
<% @questions.each do |question| %>
  <%= link_to question_path(question.id), class:"question-link" do %>
    <div class="questions">
      <div class="question-title-div">
        <p class="question-title">質問：<%= question.title %></p>
        <p class="question-genre"><%= question.genre.name %></p>
      </div>
  <% end %>
      <div class="question-main">
  <%= link_to user_path(question.user.id), class:"nickname-btn" do %>
        <div class="question-contents">
          <p class="question-headline">投稿者：</p>
          <p class="question-user"><%= question.user.nickname %></p>
        </div>
  <% end %>
  <%= link_to question_path(question.id), class:"question-link" do %>
        <div class="question-contents">
          <p class="question-headline">質問内容：</p>
          <p class="question-content"><%= question.content %></p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/questions/new.html.erb
<%= link_to 'Game Question', root_path, class: "logo" %>
<div class="question-form-main">
  <h1 class="question-form-headline">質問投稿フォーム</h1>
  <div class="question-form">
    <%= form_with model: @question, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <%= f.text_area :title, placeholder:"質問を入力してください(60字まで)", class:"title-form", maxlength:"60" %>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
      <%= f.text_area :content, placeholder:"質問の具体的な内容を入力してください", rows: "8", class:"content-form" %>
      <%= f.submit "投稿する", class:"submit-btn" %>
    <% end %>
  </div>
</div>

app/views/questions/search.html.erb
<%= render "shared/header" %>
<h1 class="search-headline">検索結果</h1>
<div class="contents row">
  <% @questions.each do |question| %>
    <%= link_to question_path(question.id), class:"question-link" do %>
      <div class="questions">
        <div class="question-title-div">
          <p class="question-headline">質問：</p>
          <p class="question-title"><%= question.title %></p>
        </div>
    <% end %>
        <div class="question-main">
    <%= link_to user_path(question.user.id), class:"nickname-btn" do %>
          <div class="question-contents">
            <p class="question-headline">投稿者：</p>
            <p class="question-user"><%= question.user.nickname %></p>
          </div>
    <% end %>
    <%= link_to question_path(question.id), class:"question-link" do %>
          <div class="question-contents">
            <p class="question-headline">質問内容：</p>
            <p class="question-content"><%= question.content %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/questions/show.html.erb
<%= render "shared/header" %>
<% if user_signed_in? && (@question.user_id == current_user.id) %>
  <div class="btn">
    <%= link_to "編集", edit_question_path(params[:id]), class:"edit-btn" %>
    <%= link_to "削除", question_path(params[:id]), method: :delete, class:"destroy-btn" %>
  </div>
<% end %>
<div class="questions-show">
  <div class="question-title-div-show">
    <p class="question-title-show">質問：<%= @question.title %></p>
    <p class="question-genre-show"><%= @question.genre.name %></p>
  </div>
  <div class="question-main-show">
    <div class="question-contents-show">
      <p class="question-headline-show">投稿者：</p>
      <p class="question-user-show"><%= @question.user.nickname %></p>
    </div>
    <div class="question-contents-show">
      <p class="question-headline-show">質問内容：</p>
      <p class="question-content-show"><%= @question.content %></p>
    </div>
  </div>
</div>

<div class="comment-main">
  <div calss="comment-form">
  <% if user_signed_in? %>
    <%= form_with model: [@question, @comment], local: true do |f| %>
      <%= f.text_area :text, placeholder: "コメントする", rows: "2", class:"text-form" %>
      <%= f.submit "SEND", class:"comment-submit-btn" %>
    <% end %>
  <% else %>
    <strong><p>※コメントの投稿には新規登録/ログインが必要です</p></strong>
  <% end %>
  </div>
  <div class="comments">
    <% @comments.each do |comment| %>
      <p class="comment"><%= comment.user.nickname %>:<%= comment.text%></p>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<div class=main>
  <div class=header-main>
    <%= link_to 'Game Question', root_path, class: "logo" %>
    <div class=login>
      <% if user_signed_in? %>
        <%= link_to current_user.nickname, user_path(current_user.id) ,class:"nickname-btn" %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout-btn" %>
      <% else %>
        <%= link_to '新規登録', new_user_registration_path, class:"register-btn" %>
        <%= link_to 'ログイン', new_user_session_path, class:"login-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>
<h1 class="question-nickname"><%= @nickname %>さんの投稿</h1>
<% @questions.each do |question| %>
  <%= link_to question_path(question.id), class:"question-link" do %>
    <div class="questions">
      <div class="question-title-div">
        <p class="question-title">質問：<%= question.title %></p>
        <p class="question-genre"><%= question.genre.name %></p>
      </div>
      <div class="question-main">
        <div class="question-contents">
          <p class="question-headline">投稿者：</p>
          <p class="question-user"><%= question.user.nickname %></p>
        </div>
        <div class="question-contents">
          <p class="question-headline">質問内容：</p>
          <p class="question-content"><%= question.content %></p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>